# ===============================================
# 1. Hello World Playbook
# ===============================================

- name: Hello World Playbook
  hosts: localhost
  connection: local
  tasks:
    - name: Print Hello
      ansible.builtin.debug:
        msg: "Hello from Ansible!"


# =================================================
# 2. Install cowsay package
# =================================================

- name: Install cowsay on localhost
  hosts: localhost
  become: true
  tasks:
    - name: Install cowsay
      ansible.builtin.package:
        name: cowsay
        state: present

#
#- name: Install Homebrew and cowsay
#  hosts: localhost
#  connection: local
#  gather_facts: false
#  tasks:
#    - name: Install Homebrew (if not installed)
#      ansible.builtin.shell: |
#        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
#      args:
#        creates: /opt/homebrew/bin/brew
#
#    - name: Ensure cowsay is installed
#      community.general.homebrew:
#        name: cowsay
#        state: present


# ===================================================
# 3. Create multiple files with variables and loops content
# ===================================================

- name: Create multiple files
  hosts: localhost
  vars:
    filenames:
      - file1.txt
      - file2.txt
      - file3.txt
  tasks:
    - name: Create files
      ansible.builtin.file:
        path: "/tmp/{{ item }}"
        state: touch
      loop: "{{ filenames }}"

# ===================================================
# 4. Run python script
# ===================================================

- name: Run Python script
  hosts: localhost
  tasks:
    - name: Execute Python script
      ansible.builtin.command: python3 ~/ansible/hello.py
      register: script_output
    
    - name: Show script output
      ansible.builtin.debug:
        var: script_output.stdout

# ===================================================
# 5. Create a file with content
# ===================================================

- name: Create a file with content
  hosts:  localhost
  tasks:
    - name: Create a file
      ansible.builtin.copy:
        dest: ~/ansible/hello.txt
        content: "This file was created by Ansible!"

# ===================================================
# 6. Create a user
# ===================================================

- name: Create a new user
  hosts: localhost
  become: true
  tasks:
    - name: Add user 'student 1'
      ansible.builtin.user:
        name: student1
        state: present

# ======================================================
# 7. Download a File from the Internet
# ======================================================

- name: Download a file
  hosts: localhost
  tasks:
    - name: Download a README from GitHub
      ansible.builtin.get_url:
        url:  https://raw.githubusercontent.com/ansible/ansible/devel/README.md
        dest: ~/ansible/ansible_readme.md

# ======================================================
# 8. Set Environment Variable
# ======================================================

- name: Set environment variable
  hosts: localhost
  tasks:
    - name: Add environment variable to .bashrc
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        line: 'export MY_VAR=ansible_is_cool'
        create: yes

# ======================================================
# 9. Install Multiple Packages
# ======================================================

- name: Install multiple packages
  hosts: localhost
  become: true
  vars:
    packages:
      - git
      - curl
      - htop
  tasks:
    - name: Install packages
      ansible.builtin.package:
        name: "{{ packages }}"
        state: present

# ======================================================
# 10. Schedule a CRON job
# ======================================================

- name: Schedule a cron job
  hosts: localhost
  become: true
  tasks:
    - name: Run backup script everyday at midnight
      ansible.builtin.cron:
        name: "daily backup"
        minute: "0"
        hour: "0"
        job: "~/ansible/README.md"

# ======================================================
# 11. Create a Simple Webpage
# ======================================================

- name: Create a simple HTML page
  hosts: localhost
  tasks:
    - name: Create index.html
      ansible.builtin.copy:
        dest: ~/ansible/index.html
        content: "<html><body><h1>Hello from Ansible!!</h1><body></html>"

# ======================================================
# 12. Install and Start Apache
# ======================================================

- name: Isntall and start Apache
  hosts: localhost
  become: true
  tasks:
    - name: Install Apache
      ansible.builtin.package:
        name: apache2
        state: present

    - name: Start Apache service
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true

#- name: Start Apache on macOS
#  command.general.homebrew_service:
#    name: httpd
#    state: started
#    enabled: true